version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cleanapp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cleanapp
      MYSQL_PASSWORD: cleanapp
      MYSQL_DATABASE: cleanapp
    ports:
      - "3306:3306"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: cleanapp-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db_data:
